apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notes-app-servicemonitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: notes-app
  endpoints:
    - port: http
      path: /metrics
      interval: 5s